config/routes.rb
Rails.application.routes.draw do
  get 'flashcards/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'kanji/index', to: 'kanji#index'
  get 'flashcards', to: 'flashcards#index'

  resources :kanji, only: [:index, :show]
  resources :puzzles, only: [:create]
  resources :user_profiles, only: [:show, :edit, :update]
  resources :upgrades, only: [:show]
  resources :practice, only: [:index]
  resources :conflicts, only: [:index, :show, :create, :update]


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  belongs_to :cell_style, class_name: "Upgrade"
  belongs_to :background_style, class_name: "Upgrade"
  belongs_to :flagged_style, class_name: "Upgrade"
  belongs_to :active_style, class_name: "Upgrade"

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_profile, only: [:show, :edit, :update]
  before_action :authorize_user_profile, only: [:edit, :update]


  def show
    @user_profile = UserProfile.find_by(user_id: current_user.id)
    @upgrades = Upgrade.all
    authorize @user_profile
  end

  def edit
  end

  def update
    # if !user_profile_params[:total_xp].nil?
    #   @user_profile.total_xp = user_profile_params[:total_xp]
    #   @user_profile.level = user_profile_params[:level]
    #   @user_profile.save
    #   redirect_to "/"
    if  params.has_key?(:upgrade)
      if Upgrade.find(params[:upgrade]).upgrade_type == "cell"
        @user_profile.update(cell_style: Upgrade.find(params[:upgrade].to_i))
        redirect_to @user_profile, notice: "Style changed."
      elsif Upgrade.find(params[:upgrade]).upgrade_type =="active"
        @user_profile.update(active_style: Upgrade.find(params[:upgrade].to_i))
        redirect_to @user_profile, notice: "Style changed."
      elsif Upgrade.find(params[:upgrade]).upgrade_type == "flagged"
        @user_profile.update(flagged_style: Upgrade.find(params[:upgrade].to_i))
        redirect_to @user_profile, notice: "Style changed."
      elsif Upgrade.find(params[:upgrade]).upgrade_type == "background"
        @user_profile.update(background_style: Upgrade.find(params[:upgrade].to_i))
        redirect_to @user_profile, notice: "Style changed."
      elsif @user_profile.update(user_profile_params)
        redirect_to @user_profile, notice: "User profile was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def set_user_profile
    @user_profile = UserProfile.find_by(user_id: current_user.id)
  end

  def authorize_user_profile
    authorize @user_profile
  end

  def user_profile_params
    params.require(:user_profile).permit(:username, :tagline, :bio, :profile_pic, :level, :total_xp, :upgrade, :type)
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
  def outline_color_for_level(level)
    case level
    when 1
      'purple'
    when 2
      'blue'
    when 3
      'green'
    when 4
      'yellow'
    when 5
      'orange'
    when 6
      'red'
    else
      'none'
    end
  end

  def upgrade_unlocked?(level, upgrade_level)
    level >= upgrade_level
  end

  def user_profile_color_options
    {
      purple: 1,
      blue: 2,
      green: 3,
      yellow: 4,
      orange: 5,
      red: 6
    }
  end
end

app/views/user_profiles/edit.html.erb
<h1>Edit <%= @user_profile.username %>'s WROND! Profile</h1>
<div class="profile-container" data-outline-color="<%= outline_color_for_level(@user_profile.level) %>">
  <%= form_with model: @user_profile, local: true do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :tagline %>
      <%= f.text_field :tagline, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_area :bio, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :profile_pic %>
      <%= f.text_field :profile_pic, class: "form-control" %>
    </div>

    <%= f.submit "Update Profile", class: "btn btn-success" %>
  <% end %>

  <%= link_to "Cancel", user_profile_path(@user_profile), class: "btn btn-secondary" %>
</div>

app/views/user_profiles/show.html.erb
<%= stylesheet_link_tag 'user_profiles/show', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="profile-container" data-outline-color="<%= outline_color_for_level(@user_profile.level) %>">
  <div class="profile-pic">
    <% if @user_profile.profile_pic.present? %>
      <%= image_tag "#{@user_profile.profile_pic}"%>
    <% else %>
      <%= image_tag("WROND.png") %>
    <% end %>
  </div>
  <h1 class="font-chicago"><%= @user_profile.username %></h1>
  <p><strong>Tagline:</strong> <%= @user_profile.tagline || "No tagline set" %></p>
  <p><strong>Bio:</strong> <%= @user_profile.bio || "No bio available" %></p>
  <p><strong>Level:</strong> <%= @user_profile.level %></p>
  <p><strong>Total XP:</strong> <%= @user_profile.total_xp %></p>
  <hr class="divider">
  <div class="edit-button">
    <%= link_to "Edit Profile", edit_user_profile_path(@user_profile), class: "btn btn-primary" %>
  </div>
</div>
<!-- Bootstrap Tabs -->
<div class="upgrades-container mt-4">
  <ul class="nav nav-tabs" id="upgradeTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="cell-tab" data-bs-toggle="tab" href="#cell" role="tab" aria-controls="cell" aria-selected="true">Background Colors</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="active-tab" data-bs-toggle="tab" href="#active" role="tab" aria-controls="active" aria-selected="false">Selected Square Colors</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="flagged-tab" data-bs-toggle="tab" href="#flagged" role="tab" aria-controls="flagged" aria-selected="false">Flagged Square Colors</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="background-tab" data-bs-toggle="tab" href="#background" role="tab" aria-controls="background" aria-selected="false">Backgrounds</a>
    </li>
  </ul>
  <div class="tab-content mt-4" id="upgradeTabContent">
    <!-- Background Colors Tab -->
    <div class="tab-pane fade show active" id="cell" role="tabpanel" aria-labelledby="cell-tab">
      <div class="upgrades-box d-flex">
        <% @upgrades.where(upgrade_type: "cell").each do |upgrade| %>
          <% if @user_profile.level.to_i >= upgrade.level.to_i %>
            <%= button_to user_profile_path(@user_profile), method: :patch, params: { upgrade: upgrade }, remote: true do %>
              <div class="upgradeCard selectable <%= "selected" if @user_profile.cell_style == upgrade %>">
                <h5><%= upgrade.name %></h5>
                <hr class="divider">
                <p><%= upgrade.description %></p>
              </div>
            <% end %>
          <% else %>
            <div class="upgradeCard locked">
              <h5><%= upgrade.name %></h5>
              <hr class="divider">
              <p><%= upgrade.description %></p>
              <hr class="divider">
              <p class="unlock">Unlocked at Level <%= upgrade.level %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- Selected Square Colors Tab -->
    <div class="tab-pane fade" id="active" role="tabpanel" aria-labelledby="active-tab">
      <div class="upgrades-box d-flex">
        <% @upgrades.where(upgrade_type: "active").each do |upgrade| %>
          <% if @user_profile.level.to_i >= upgrade.level.to_i %>
            <%= button_to user_profile_path(@user_profile), method: :patch, params: { upgrade: upgrade }, remote: true do %>
              <div class="upgradeCard selectable <%= "selected" if @user_profile.active_style == upgrade %>">
                <h5><%= upgrade.name %></h5>
                <hr class="divider">
                <p><%= upgrade.description %></p>
              </div>
            <% end %>
          <% else %>
            <div class="upgradeCard locked">
              <h5><%= upgrade.name %></h5>
              <hr class="divider">
              <p><%= upgrade.description %></p>
              <hr class="divider">
              <p class="unlock">Unlocked at Level <%= upgrade.level %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- Flagged Square Colors Tab -->
    <div class="tab-pane fade" id="flagged" role="tabpanel" aria-labelledby="flagged-tab">
      <div class="upgrades-box d-flex">
        <% @upgrades.where(upgrade_type: "flagged").each do |upgrade| %>
          <% if @user_profile.level.to_i >= upgrade.level.to_i %>
            <%= button_to user_profile_path(@user_profile), method: :patch, params: { upgrade: upgrade }, remote: true do %>
              <div class="upgradeCard selectable <%= "selected" if @user_profile.flagged_style == upgrade %>">
                <h5><%= upgrade.name %></h5>
                <hr class="divider">
                <p><%= upgrade.description %></p>
              </div>
            <% end %>
          <% else %>
            <div class="upgradeCard locked">
              <h5><%= upgrade.name %></h5>
              <hr class="divider">
              <p><%= upgrade.description %></p>
              <hr class="divider">
              <p class="unlock">Unlocked at Level <%= upgrade.level %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- Backgrounds Tab -->
    <div class="tab-pane fade" id="background" role="tabpanel" aria-labelledby="background-tab">
      <div class="upgrades-box d-flex">
        <% @upgrades.where(upgrade_type: "background").each do |upgrade| %>
          <% if @user_profile.level.to_i >= upgrade.level.to_i %>
            <%= button_to user_profile_path(@user_profile), method: :patch, params: { upgrade: upgrade }, remote: true do %>
              <div class="upgradeCard selectable <%= "selected" if @user_profile.background_style == upgrade %>">
                <h5><%= upgrade.name %></h5>
                <hr class="divider">
                <p><%= upgrade.description %></p>
              </div>
            <% end %>
          <% else %>
            <div class="upgradeCard locked">
              <h5><%= upgrade.name %></h5>
              <hr class="divider">
              <p><%= upgrade.description %></p>
              <hr class="divider">
              <p class="unlock">Unlocked at Level <%= upgrade.level %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>