config/routes.rb
Rails.application.routes.draw do
  get 'flashcards/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'kanji/index', to: 'kanji#index'
  get 'flashcards', to: 'flashcards#index'

  resources :kanji, only: [:index, :show]
  resources :puzzles, only: [:create]
  resources :user_profiles, only: [:show, :edit, :update]
  resources :upgrades, only: [:show]
  resources :practice, only: [:index]
  resources :conflicts, only: [:index, :show, :create, :update]


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  has_many :puzzles, dependent: :destroy
  has_many :conflicts
end

app/controllers/kanji_controller.rb
class KanjiController < ApplicationController

# lookin good
  def index
    @kanji = policy_scope(Kanji)
    @puzzles = Puzzle.where(user: current_user)

    @n5_done = Kanji.joins(:puzzles).distinct.where(jlptLevel: "5")
    @n5_total = Kanji.where(jlptLevel: "5")

    @n4_done = Kanji.joins(:puzzles).distinct.where(jlptLevel: "4")
    @n4_total = Kanji.where(jlptLevel: "4")

    @n3_done = Kanji.joins(:puzzles).distinct.where(jlptLevel: "3")
    @n3_total = Kanji.where(jlptLevel: "3")

    @n2_done = Kanji.joins(:puzzles).distinct.where(jlptLevel: "2")
    @n2_total = Kanji.where(jlptLevel: "2")

    @n1_done = Kanji.joins(:puzzles).distinct.where(jlptLevel: "1")
    @n1_total = Kanji.where(jlptLevel: "1")

    @all_done = Kanji.joins(:puzzles).distinct
    @all_total = Kanji.count
  end

  def show
    @next_kanji = Kanji.find(params[:id].to_i + 1)
    @kanji = Kanji.find(params[:id])
    @user_profile = UserProfile.find(current_user.user_profile.id)
    @puzzles = Puzzle.where("kanji_id = ?", @kanji.id).order("time").limit(10)
    @puzzle = Puzzle.new
    authorize @user_profile

    client = OpenAI::Client.new
    chatgpt_response = client.chat(parameters: {
      model: "gpt-4o-mini",
      messages: [{
        role: "system",
        content: "Act as Wrondarou, an 8-bit pixelated samurai who gives cryptic but short helpful kanji hints.\nFormat hints as follows:\n A poetic, but accurate haiku-esque reference to the meaning about the kanji.\nGenerate a hint for this kanji: #{@kanji.kanji}\nMake it accurate and less cryptic"
      }]
    })
    @content = chatgpt_response["choices"][0]["message"]["content"]
  end

  def kanji?(input)
    kanji = Kanji.where(kanji: input)
    current_user.puzzles.where(kanji_id: kanji).count > 0
  end

end

app/views/kanji/_conclussion.html.erb
<div class="popup hidden" id="conclussionModal" tabindex="-1" role="dialog" aria-labelledby="conclussionModalLabel" aria-hidden="true">
  <div class="popup-dialog" role="document">
    <div class="popup-content justify-content-center">
      <div class="popup-header">
        <h5 class="popup-title" id="conclussionpopupLabel"></h5>
      </div>
      <div class="popup-body d-flex justify-content-between px-3">
        <p class="px-3 text-large">XP <span id="xp-value">0 </span></p>
        <p><%= image_tag "clock.png" %>  <span id="time-span"></span></p>
      </div>
      <div class="level-up hidden" id="level-up">
        <div class="popup-body d-flex justify-content-center" >
          <p>Level Up! <span id="level-span">1</span> &rarr; <span id="level-up-span">2 </span></p>
        </div>
        <div class="popup-body d-flex justify-content-center" id="level-up-image">
          <%= image_tag "celebrate.GIF", class: "celebrate" %>
        </div>
      </div>
      <div class="popup-footer">
        <button type="button" class="btn btn-secondary popup-button" id="popup-button" data-bs-dismiss="popup">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/kanji/_highscore.html.erb
<ul>
  <% puzzles.each do |puzzle| %>
    <% minutes = (puzzle.time / 60) < 10 ? "0#{(puzzle.time / 60)}" : puzzle.time / 60 %>
    <% seconds = (puzzle.time % 60) < 10 ? "0#{(puzzle.time % 60)}" : puzzle.time % 60%>
    <li class="list"><%= minutes %>:<%= seconds %> - <%= puzzle.user.user_profile.username %></li>
  <% end %>
</ul>

app/views/kanji/index.html.erb
<div class="level-buttons">
  <div class="button-box">
    <div class="crown"> <%= image_tag "crown.png", id: "crown_n1", class:"hidden"%> </div>
    <div class="level-filter level-1">N1</div>
    <span class="level-filter level-1 hidden"><span id="n1_done"><%=@n1_done.count%></span>/<span id="n1_total"><%= @n1_total.count%></span>
  </div>
  <div class="button-box">
    <div class="crown"> <%= image_tag "crown.png", id: "crown_n2", class:"hidden" %> </div>
    <div class="level-filter level-2">N2</div>
    <span class="level-filter level-2 hidden"><span id="n2_done"><%=@n2_done.count%></span>/<span id="n2_total"><%= @n2_total.count%></span>
  </div>
  <div class="button-box">
    <div class="crown"> <%= image_tag "crown.png", id: "crown_n3", class:"hidden" %> </div>
    <div class="level-filter level-3">N3</div>
    <span class="level-filter level-3 hidden"><span id="n3_done"><%=@n3_done.count%></span>/<span id="n3_total"><%= @n3_total.count%></span>
  </div>
  <div class="button-box">
    <div class="crown"> <%= image_tag "crown.png", id: "crown_n4", class:"hidden" %> </div>
    <div class="level-filter level-4">N4</div>
    <span class="level-filter level-4 hidden"><span id="n4_done"><%=@n4_done.count%></span>/<span id="n4_total"><%= @n4_total.count%></span>
  </div>
  <div class="button-box">
    <div class="crown"> <%= image_tag "crown.png", id: "crown_n5", class:"hidden" %> </div>
    <div class="level-filter level-5">N5</div>
    <span class="level-filter level-5 hidden"><span id="n5_done"><%=@n5_done.count%></span>/<span id="n5_total"><%= @n5_total.count%></span>
  </div>
  <div class="button-box">
    <div class="crown"> <%= image_tag "crown.png", id: "crown_all", class:"hidden"  %> </div>
    <div class="level-filter level-all">All!</div>
    <span class="level-filter level-all hidden"><span id="all_done"><%=@all_done.count%></span>/<span id="all_total"><%= @kanji.count%></span>
  </div>
</div>

<div class="main-container" data-controller="index-side-menu">
  <div class="left-side">
    <div class="info-card">
      <div class="kanji-display-container"><p><span id="kanji-display">?</span></p></div>
      <p><strong>Meaning:</strong> <span id="meaning">?</span></p>
      <p><strong>Onyomi:</strong> <span id="onyomi" class="kanji-font">?</span></p>
      <p><strong>Kunyomi:</strong> <span id="kunyomi" class="kanji-font">?</span></p>
      <p><strong>Stroke Count:</strong> <span id="stroke-count">?</span></p>
      <p><strong>JLPT Level:</strong> <span id="jlpt-level">?</span></p>

      <div class="button-container">
        <button type="button" class="play-button-right" id="play-btn" disabled>Play!</button>
        <input type="hidden" id="selected-kanji" name="selected-kanji">
      </div>
    </div>

    <% @kanji.each do |kanji| %>
      <div class="hidden-kanji-data"
            data-kanji="<%= kanji.kanji %>"
            data-meaning="<%= kanji.meaning %>"
            data-onyomi="<%= kanji.onyomi[1..-2] %>"
            data-kunyomi="<%= kanji.kunyomi %>"
            data-stroke-count="<%= kanji.stroke_count %>"
            data-jlpt="<%= kanji.jlptLevel %>"
            data-solved="<%= @puzzles.any? {|p| p.kanji == kanji} ? 1 : 0 %>">
      </div>
    <% end %>
  </div>

   <div class="right-side">
    <div class="card-container index-bottom-fade" data-controller="fade">
      <% (@all_done).each_with_index do |kanji, index| %>
        <% stroke_count = kanji.stroke_count %>
        <% stars = case stroke_count
                   when 1..2 then "★☆☆☆☆"
                   when 3..4 then "★★☆☆☆"
                   when 5..10 then "★★★☆☆"
                   when 11..12 then "★★★★☆"
                   else "★★★★★"
                   end %>

        <div class="card" data-kanji="<%= kanji.kanji %>"
             data-meaning="<%= kanji.meaning.join(" ") %>"
             data-onyomi="<%= kanji.onyomi[1..-2] %>"
             data-kunyomi="<%= kanji.kunyomi[1..-2] %>"
             data-stroke-count="<%= kanji.stroke_count %>"
             data-jlpt="<%= kanji.jlptLevel %>"
             data-url="<%= kanji_path(kanji) %>"
             data-solved="<%= @puzzles.any? {|p| p.kanji == kanji} ? 1 : 0 %>">

          <div class="stars"><%= stars %></div>
          <div class="level level-<%= kanji.jlptLevel %>">N<%= kanji.jlptLevel %></div>
          <div class="white-box-for">
            <div class="question-mark">?</div>
          </div>
        </div>
      <% end %>

      <% not_done = (
        (@n5_total - @n5_done)[..10] +
        (@n4_total - @n4_done)[..10] +
        (@n3_total - @n3_done)[..10] +
        (@n2_total - @n2_done)[..10] +
        (@n1_total - @n1_done)[..10]
        ) %>
      <% (not_done).each_with_index do |kanji, index| %>
        <% stroke_count = kanji.stroke_count %>
        <% stars = case stroke_count
                   when 1..2 then "★☆☆☆☆"
                   when 3..5 then "★★☆☆☆"
                   when 6..8 then "★★★☆☆"
                   when 9..12 then "★★★★☆"
                   else "★★★★★"
                   end %>

        <div class="card" data-kanji="<%= kanji.kanji %>"
             data-meaning="<%= kanji.meaning %>"
             data-onyomi="<%= kanji.onyomi %>"
             data-kunyomi="<%= kanji.kunyomi %>"
             data-stroke-count="<%= kanji.stroke_count %>"
             data-jlpt="<%= kanji.jlptLevel %>"
             data-url="<%= kanji_path(kanji) %>"
             data-solved="<%= @puzzles.any? {|p| p.kanji == kanji} ? 1 : 0 %>">

          <!-- Displaying dynamic stars -->
          <div class="stars"><%= stars %></div>
          <div class="level level-<%= kanji.jlptLevel %>">N<%= kanji.jlptLevel %></div>
          <div class="white-box-for">
            <div class="question-mark">?</div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/kanji/show.html.erb
<div data-controller="hint">
  <div class="button_box d-flex justify-content-center">
    <%= link_to "Back", kanji_index_path, class: "level-filter level-1 m-3 back" %>
    <%= link_to "Another Puzzle?", kanji_path(@next_kanji), class: "hidden level-filter level-4 m-3 another", id: "next_link" %>
    <%= link_to "Unlocked Kanji", flashcards_path, class: "hidden level-filter level-2 m-3 flashcards", id: "unlocked_kanji_link" %>
  </div>
  <div class="container d-flex">
    <div>
      <div class="spacer"></div>
      <% turbo_stream_from "highscores#{@kanji.id}"%>
      <div class="highscores" id="highscores<%=@kanji.id%>">
        <%= render "puzzles/puzzle", puzzles: @puzzles %>
      </div>
    </div>
    <div class="puzzle-window">
      <div class="puzzle"
      id="puzzle"
      data-controller="puzzle"
      data-puzzle-target="rootDiv"
      data-puzzle-variable="<%=@kanji.puzzleInfo.to_json%>"
      data-puzzle-cell_style="<%= @user_profile.cell_style.name %>"
      data-puzzle-background_style="<%= @user_profile.background_style.name %>"
      data-puzzle-active_style="<%= @user_profile.active_style.name %>"
      data-puzzle-flagged_style="<%= @user_profile.flagged_style.name %>"
      data-puzzle-base_xp="<%= @current_xp %>"
      >
      </div>
    </div>
    <div>
      <div class="spacer"></div>
      <div class="kanji-data" id="kanji-data">
        <div class="kanji-display-container">
          <p><span id="kanji-display"><%= @kanji.kanji %></span></p>
        </div>
        <p><strong>Meaning:</strong> <span id="meaning"><%= @kanji.meaning[..2].join(" ").gsub("[", "").gsub("]", "") %></span></p>
        <p><strong>Onyomi:</strong> <span id="onyomi" class="kanji-font"><%= @kanji.onyomi[1..-2]%></span></p>
        <p><strong>Kunyomi:</strong> <span id="kunyomi" class="kanji-font"><%= @kanji.kunyomi[1..-2] %></span></p>
        <p><strong>JLPT Level:</strong> <span id="jlpt-level"><%= @kanji.jlptLevel %></span></p>
      </div>
    </div>
  </div>
  <div class="hidden">
    <%= simple_form_for @puzzle, remote: true, html: { id: :puzzle_form } do |f| %>
      <%= f.input :time ,input_html: {id: "time_field" }%>
      <%= f.input :kanji_id, input_html: {value: @kanji.id } %>
      <%= f.input :total_xp ,input_html: {id: "xp_field", value: @user_profile.total_xp }%>
      <%= f.input :level, input_html: {id: "level_field", value: @user_profile.level } %>
      <%= f.button :submit, id: "puzzle-submit" %>
    <% end %>
  </div>
  <div>
    <%= render "kanji/conclussion" %>
  </div>
  <div class="ask-wrondarou-btn hidden" data-target="hint">
    <span id="click_me">
      Click on Wrondarou-sama for a hint...
    </span>
    <div class="words-of-wisdom" data-hint-target="hint">
      <p><%= @content %></p>
    </div>
  </div>
  <div class="gif-container-bottom" data-action="click->hint#appear">
    <%= image_tag asset_path("click-me-wrondarou.GIF"),
                class: "game-gif-bottom",
                data:{hint_target: "wrondarou", action: "click->hint#appear"}
  %>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    let gif = document.querySelector(".game-gif-bottom");

    // Ensure the GIF is visible when the page loads
    gif.style.display = "block";
  });
</script>